# Generated by Django 3.2.13 on 2022-06-09 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrifter', '0003_gasprices_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasprices',
            name='address',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='gasprices',
            name='city',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='thrifter.cities'),
        ),
    ]
