# Generated by Django 3.2.13 on 2022-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifter', '0004_auto_20220609_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasprices',
            name='address',
        ),
        migrations.AddField(
            model_name='cities',
            name='address',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
