# Generated by Django 3.2.13 on 2022-06-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrifter', '0006_auto_20220609_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='gasprices',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thrifter.station'),
        ),
    ]
