# Generated by Django 3.2.13 on 2022-06-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrifter', '0007_auto_20220609_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasprices',
            name='city',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='thrifter.cities'),
        ),
        migrations.AlterField(
            model_name='gasprices',
            name='station',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='thrifter.station'),
        ),
    ]
